# Archivo: .devcontainer/Dockerfile
FROM mcr.microsoft.com/devcontainers/typescript-node:20

# Aquí en el futuro podemos agregar instalaciones extra si la app lo requiere.
# Por ahora, solo exponemos el puerto que usará Express.
EXPOSE 3000